version: '3'

services:
  user_api:
    image: python
    ports:
      - 8081:8081
    environment: 
      - PACT_BROKER_URL
      - PACT_BROKER_TOKEN
    volumes: 
      - .:/src
    working_dir: /src
    command: tail -f /dev/null